# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'Watchin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Watchin
pod 'Alamofire', '~> 5.5'
pod 'AlamofireImage', '~> 4.1'
  target 'WatchinTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
